Add python module support

diff --git a/relinux b/relinux
--- a/relinux
+++ b/relinux
@@ -21,11 +21,11 @@ export TRUE=0
 export FALSE=1
 if [ -z $RELINUXCONFDIR ]
 then
-	export RELINUXCONFDIR=/etc/relinux
+	export RELINUXCONFDIR=/etc/relinux/
 fi
 if [ -z $RELINUXLIBDIR ]
 then
-	export RELINUXLIBDIR=/usr/lib/relinux
+	export RELINUXLIBDIR=/usr/lib/relinux/
 fi
 export RELINUXEXECFILE=$RELINUXLIBDIR/relinux/__main__.py
 if [[ "$RELINUXCONFDIR" == "MAKE""FILE_ENTER_CONF_DIR" || \
@@ -64,6 +64,17 @@ fi
 if [ $GIVEUP -eq $TRUE ]
 then
 	echo "Warning: Python 3 is being used. Relinux might have unexpected behavior because of this"
+	$PYEXEC -c 'import apt' &>/dev/null
+	if [ $? -ne 0 ]
+	then
+		echo "Relinux needs python3-apt. Please wait while relinux tries to install this"
+		sudo apt-get install -y python3-apt
+		if [ $? -ne 0 ]
+		then
+			echo "An error has occurred while trying to install python3-apt"
+			exit 1
+		fi
+	fi
 fi
 
 $PYEXEC $RELINUXEXECFILE $@
